# Generated by Django 3.2.9 on 2021-11-29 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211129_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 11, 38, 26, 948265, tzinfo=utc)),
        ),
    ]
